name: source -> main (via hugo)

on:
  push:
    branches:
      - main #source
  
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "chikin.net"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.141.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      
      # checkout files in source branch
      - name: checkout source
        uses: actions/checkout@v4
        with:
          ref: main #source
      
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify
      
      # tar files before uploading
      - name: tar files
        run: tar -cvf public.tar ./public
      
      # upload generated content (./public) as artefact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publictar
          path: public.tar
          overwrite: true
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # checkout files in main branch
      - name: checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      
      # clear it
      - name: clear current
        run: rm -rf *

      # download tar file containing content
      - name: download artefact
        uses: actions/download-artifact@v4
        with:
          name: publictar

      # extract files from tar
      - name: extract files
        run: tar -xvf public.tar

      # test output
      - name: test output
        run: ls -R
      
      # commit and push new files to main branch
      #- name: Commit report
      #  run: |
      #    git config --global user.name 'Your Name'
      #    git config --global user.email 'your-username@users.noreply.github.com'
      #    git commit -am "Automated report"
      #    git push
      # push to main branch
